import sharp from 'sharp'

export const MAX_FILE_SIZE = 5 * 1024 * 1024 // 5MB

export async function validateAndConvertToWebP(file: File): Promise<{ buffer: Buffer; error?: never } | { buffer?: never; error: string }> {
  if (file.size > MAX_FILE_SIZE) {
    return { error: `File is too large. Maximum allowed size is 5MB (received: ${(file.size / 1024 / 1024).toFixed(1)}MB)` }
  }

  const allowed = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
  if (!allowed.includes(file.type)) {
    return { error: 'Unsupported format. Use PNG, JPG, WebP or GIF.' }
  }

  const bytes = await file.arrayBuffer()
  const input = Buffer.from(bytes)

  // SVG is not converted to WebP; serve it directly.
  if (file.type === 'image/svg+xml') {
    return { buffer: input }
  }

  const buffer = await sharp(input)
    .webp({ quality: 85 })
    .toBuffer()

  return { buffer }
}

/**
 * convertBufferToWebP - converts a raw image Buffer to WebP at quality 85.
 * Sibling to validateAndConvertToWebP; accepts Buffer input (for AI-generated bytes).
 * Used by Phase 10 image seeding routes. Sharp is already the installed converter.
 */
export async function convertBufferToWebP(input: Buffer): Promise<Buffer> {
  return sharp(input).webp({ quality: 85 }).toBuffer()
}
