// Launch-checklist signals: what the platform can already tell about a
// restaurant's public menu from data it holds (active flag, custom domain, SEO
// overrides, local SEO). Advisory only — never ticks anything by
// itself. Pure, so it is unit-tested directly (launch-checklist-signals.test.ts).
import type { LaunchChecklistSignal } from '@/lib/launch-checklist'

const nonEmpty = (value: string | null | undefined): boolean => typeof value === 'string' && value.trim().length > 0

export interface LaunchChecklistSignalInput {
  isActive: boolean
  customDomain: string | null
  customDomainVerified: boolean
  settings: {
    seo_title: string | null
    seo_description: string | null
    seo_og_image_url: string | null
    seo_noindex: boolean | null
    logo_url: string | null
    phone: string | null
    address: string | null
    city: string | null
    latitude: number | null
  } | null
}

export function deriveLaunchChecklistSignals(input: LaunchChecklistSignalInput): Record<string, LaunchChecklistSignal> {
  const signals: Record<string, LaunchChecklistSignal> = {}
  const s = input.settings

  signals.custom_domain = input.customDomain && input.customDomainVerified
    ? { ok: true, value: input.customDomain }
    : input.customDomain
      ? { ok: false, reason: 'domainUnverified', value: input.customDomain }
      : { ok: false, reason: 'noDomain' }

  const noindex = Boolean(s?.seo_noindex)
  signals.site_published = !input.isActive
    ? { ok: false, reason: 'tenantNotActive' }
    : noindex ? { ok: false, reason: 'robotsNoindex' } : { ok: true }
  // robots.txt and sitemap.xml are generated per request for every active
  // restaurant (src/app/(public)/[slug]/robots.txt, sitemap.xml).
  signals.robots_txt = input.isActive ? { ok: true, reason: 'robotsAllow' } : { ok: false, reason: 'robotsInactive' }
  signals.sitemap_xml = input.isActive ? { ok: true, reason: 'autoGenerated' } : { ok: false, reason: 'robotsInactive' }

  if (!s) return signals

  signals.meta_titles = nonEmpty(s.seo_title) && nonEmpty(s.seo_description)
    ? { ok: true }
    : { ok: false, reason: 'usingFallback' }
  // Without an override a branded Open Graph card is generated at runtime, so
  // sharing always shows something sensible.
  signals.og_image = nonEmpty(s.seo_og_image_url) ? { ok: true } : { ok: true, reason: 'ogGenerated' }
  signals.favicon = nonEmpty(s.logo_url) ? { ok: true } : { ok: false, reason: 'noFavicon' }
  signals.structured_data = nonEmpty(s.city) && s.latitude != null
    ? { ok: true, reason: 'localSeoSet' }
    : { ok: false, reason: 'noLocalSeo' }
  signals.nap = nonEmpty(s.phone) && nonEmpty(s.address)
    ? { ok: true }
    : { ok: false, reason: !nonEmpty(s.phone) ? 'noPhone' : 'noAddress' }

  return signals
}
